source 'https://github.com/CocoaPods/Specs.git'

target 'JVMenuButton', :exclusive => true do
  pod "JVMenuButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JVMenuButton", :path => "../"

  
end
